version: '3.8'

services:
  backend:
    build:
      context: ./backend
    # Only expose to internal network, not to host
    networks:
      - app-network

  webui:
    build:
      context: ./webui
    # Only expose to internal network, not to host
    networks:
      - app-network

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"  # Only expose the API gateway port
    networks:
      - app-network
    depends_on:
      - backend
      - webui

networks:
  app-network:
    driver: bridge
